# Generated by Django 5.2.10 on 2026-01-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("codigo", models.CharField(blank=True, max_length=20, null=True)),
                ("semestre", models.CharField(blank=True, max_length=20, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
                "ordering": ["nombre"],
            },
        ),
    ]
