# Generated by Django 6.0.1 on 2026-01-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('aula', 'Aula Regular'), ('laboratorio', 'Laboratorio'), ('auditorio', 'Auditorio'), ('sala_conferencias', 'Sala de Conferencias')], default='aula', max_length=30)),
                ('bloque', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=10)),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('tiene_proyector', models.BooleanField(default=False)),
                ('tiene_computadores', models.BooleanField(default=False)),
                ('tiene_aire_acondicionado', models.BooleanField(default=False)),
                ('tiene_smart_tv', models.BooleanField(default=False)),
                ('tiene_audio', models.BooleanField(default=False)),
                ('tiene_wifi', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
                'ordering': ['bloque', 'piso', 'nombre'],
            },
        ),
    ]
