# Generated by Django 5.2.10 on 2026-01-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="salones/"),
        ),
    ]
